### ISSUE TITLE
Error uploading files

### ISSUE THREAD

**Issue by Bioso** [adswa/multimatch_gaze#29]
I have been trying to use the multimatch from the command line with this command: multimatch-gaze p3.csv p30.csv 2880 2160 

I am getting the following error:

Traceback (most recent call last):
  File "c:\python37\Lib\runpy.py", line 193, in _run_module_as_main   "__main__", mod_spec)
  File "c:\python37\Lib\runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "C:\Users\ZoyaDare\Envs\Coefficient\Scripts\multimatch-gaze.exe\__main__.py", line 9, in <module>
  File "c:\users\zoyadare\envs\coefficient\lib\site-packages\multimatch_gaze\multimatch_gaze.py", line 977, in main    usecols=(0, 1, 2)
  File "c:\users\zoyadare\envs\coefficient\lib\site-packages\numpy\lib\npyio.py", line 2322, in recfromcsv    output = genfromtxt(fname, **kwargs)
  File "c:\users\zoyadare\envs\coefficient\lib\site-packages\numpy\lib\npyio.py", line 2158, in genfromtxt    dtype.names = names
ValueError: must replace all names at once with a sequence of length 3

It seems to be a problem with the numpy recfromcsv command in the main function. I can't seem to figure out what is wrong though. Any help is highly appreciated! My data files are attached (I had them as csv files but those won't upload here so I changed them to txt files). 

[p30.txt](https://github.com/adswa/multimatch_gaze/files/3286438/p30.txt)
[p3.txt](https://github.com/adswa/multimatch_gaze/files/3286439/p3.txt)

Thank you for your help!

**Comment by adswa** [comment]
Hi @Bioso, 

I only took a very quick glimpse (so please follow up on this if that does not help :-) ), and it seems like your .tsv files do not have a tab-separated header. All header items are in one single column separated by spaces (the remaining rows of the files look good). Fixing the headers makes it work for me, let me know if that fixes it for you!

**Comment by adswa** [comment]
However, you might want to consider using shorter scanpaths, if it is feasible for your research question -- see #28

**Comment by adswa** [comment]
I'm closing this as I haven't heard about additional problems, but feel free to reopen if necessary.

**Comment by Bioso** [comment]
Thank you for your help! I fixed the headers and the problem was resolved! So sorry it took so long to reply.

**Comment by adswa** [comment]
No problem at all. :-)
